// <auto-generated />
using System;
using Gasparzinho.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gasparzinho.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913155735_FirstA")]
    partial class FirstA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.Ban", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("GroupId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("group_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("session_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("bans", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.Contact", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Jid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("jid");

                    b.Property<string>("PushName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("push_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId", "Jid");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.CustomCommand", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TriggerWord")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("trigger_word");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TriggerWord")
                        .IsUnique();

                    b.ToTable("custom_commands", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.GroupSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<bool>("AiEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ai_enabled");

                    b.Property<bool>("BanLinks")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ban_links");

                    b.Property<bool>("BanMedia")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ban_media");

                    b.Property<bool>("BanNsfw")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ban_nsfw");

                    b.Property<bool>("BanProfanity")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ban_profanity");

                    b.Property<bool>("BanViewOnce")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ban_viewonce");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("FloodCloseMin")
                        .HasColumnType("int")
                        .HasColumnName("flood_close_min");

                    b.Property<int>("FloodLimit")
                        .HasColumnType("int")
                        .HasColumnName("flood_limit");

                    b.Property<int>("FloodPeriodMin")
                        .HasColumnType("int")
                        .HasColumnName("flood_period_min");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("group_id");

                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("group_name");

                    b.Property<bool>("InactivityAnnounce")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("inactivity_announce");

                    b.Property<int>("InactivityDays")
                        .HasColumnType("int")
                        .HasColumnName("inactivity_days");

                    b.Property<bool>("InactivityEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("inactivity_enabled");

                    b.Property<DateTime?>("InactivityLastRunAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("inactivity_last_run_at");

                    b.Property<string>("InactivityReason")
                        .HasColumnType("text")
                        .HasColumnName("inactivity_reason");

                    b.Property<bool>("IsManaged")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_managed");

                    b.Property<string>("LockDays")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lock_days");

                    b.Property<bool>("LockEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lock_enabled");

                    b.Property<string>("LockEnd")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("lock_end");

                    b.Property<string>("LockReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("lock_reason");

                    b.Property<string>("LockStart")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("lock_start");

                    b.Property<string>("ModerationMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("moderation_mode");

                    b.Property<string>("MsgBan")
                        .HasColumnType("text")
                        .HasColumnName("msg_ban");

                    b.Property<string>("MsgWarn")
                        .HasColumnType("text")
                        .HasColumnName("msg_warn");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("session_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("WarnChances")
                        .HasColumnType("int")
                        .HasColumnName("warn_chances");

                    b.Property<bool>("WelcomeEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("welcome_enabled");

                    b.Property<string>("WelcomeMessage")
                        .HasColumnType("text")
                        .HasColumnName("welcome_message");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "GroupId")
                        .IsUnique();

                    b.ToTable("group_settings", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.MemberActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("group_id");

                    b.Property<string>("Jid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("jid");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_message_at");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("session_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "GroupId", "Jid")
                        .IsUnique();

                    b.HasIndex("SessionId", "GroupId", "LastMessageAt");

                    b.ToTable("member_activity", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.ModerationSuggestion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("AiReason")
                        .HasColumnType("text")
                        .HasColumnName("ai_reason");

                    b.Property<float?>("Confidence")
                        .HasColumnType("float")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectedReason")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("detected_reason");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("group_id");

                    b.Property<string>("GroupName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("group_name");

                    b.Property<string>("MessageId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageText")
                        .HasColumnType("text")
                        .HasColumnName("message_text");

                    b.Property<string>("PromptUsed")
                        .HasColumnType("text")
                        .HasColumnName("prompt_used");

                    b.Property<string>("ReplyTemplate")
                        .HasColumnType("text")
                        .HasColumnName("reply_template");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("SenderJid")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sender_jid");

                    b.Property<string>("SenderPhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sender_phone");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("suggested_action");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("SessionId", "GroupId", "Status");

                    b.ToTable("moderation_suggestions", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("kind");

                    b.Property<string>("Metadata")
                        .HasColumnType("text")
                        .HasColumnName("metadata");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("read_at");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("severity");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("TenantId", "ReadAt");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Features")
                        .HasColumnType("text")
                        .HasColumnName("features");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxGroups")
                        .HasColumnType("int")
                        .HasColumnName("max_groups");

                    b.Property<int?>("MaxGroupsPerSession")
                        .HasColumnType("int")
                        .HasColumnName("max_groups_per_session");

                    b.Property<int>("MaxSessions")
                        .HasColumnType("int")
                        .HasColumnName("max_sessions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.ProfanityWord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Word")
                        .IsUnique();

                    b.ToTable("profanity_words", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.SuperAdmin", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("super_admins", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.SystemAiConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text")
                        .HasColumnName("api_key");

                    b.Property<bool>("CreditsExhausted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("credits_exhausted");

                    b.Property<bool>("DegradedMode")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("degraded_mode");

                    b.Property<string>("DegradedReason")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("degraded_reason");

                    b.Property<DateTime?>("DegradedSince")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("degraded_since");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<DateTime?>("ExpectedRecoveryAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expected_recovery_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("NsfwPrompt")
                        .HasColumnType("text")
                        .HasColumnName("nsfw_prompt");

                    b.Property<string>("ProfanityPrompt")
                        .HasColumnType("text")
                        .HasColumnName("profanity_prompt");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provider");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("system_ai_config", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.Tenant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PlanExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("plan_expires_at");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("plan_id");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.TenantAiConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasColumnType("text")
                        .HasColumnName("api_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("ModerationApiKey")
                        .HasColumnType("text")
                        .HasColumnName("moderation_api_key");

                    b.Property<bool>("ModerationEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("moderation_enabled");

                    b.Property<string>("ModerationModel")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("moderation_model");

                    b.Property<string>("ModerationProvider")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("moderation_provider");

                    b.Property<string>("NsfwPrompt")
                        .HasColumnType("text")
                        .HasColumnName("nsfw_prompt");

                    b.Property<string>("ProfanityPrompt")
                        .HasColumnType("text")
                        .HasColumnName("profanity_prompt");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provider");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TriggerKeyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("trigger_keyword");

                    b.Property<string>("TriggerMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("trigger_mode");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("ai_configs", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId", "Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.WaSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("QrCode")
                        .HasColumnType("mediumtext")
                        .HasColumnName("qr_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.Warning", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("id");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("group_id");

                    b.Property<string>("LastReason")
                        .HasColumnType("text")
                        .HasColumnName("last_reason");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("phone");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("session_id");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "GroupId", "Phone")
                        .IsUnique();

                    b.ToTable("warnings", (string)null);
                });

            modelBuilder.Entity("Gasparzinho.Web.Data.Entities.User", b =>
                {
                    b.HasOne("Gasparzinho.Web.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
